/*
 * Tesla Model S JSON API
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.github.jonahwh.tesla_api_client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ChargeStateResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-18T04:11:52.708-07:00")
public class ChargeStateResponse {
  @SerializedName("response")
  private Object response = null;

  public ChargeStateResponse response(Object response) {
    this.response = response;
    return this;
  }

   /**
   * 
   * @return response
  **/
  @ApiModelProperty(example = "{\"charging_state\":\"Complete\",\"charge_to_max_range\":false,\"max_range_charge_counter\":0,\"fast_charger_present\":false,\"battery_range\":239.02,\"est_battery_range\":155.79,\"ideal_battery_range\":275.09,\"battery_level\":91,\"battery_current\":-0.6,\"charge_starting_range\":null,\"charge_starting_soc\":null,\"charger_voltage\":0,\"charger_pilot_current\":40,\"charger_actual_current\":0,\"charger_power\":0,\"time_to_full_charge\":null,\"charge_rate\":-1,\"charge_port_door_open\":true}", required = true, value = "")
  public Object getResponse() {
    return response;
  }

  public void setResponse(Object response) {
    this.response = response;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargeStateResponse chargeStateResponse = (ChargeStateResponse) o;
    return Objects.equals(this.response, chargeStateResponse.response);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargeStateResponse {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

