/*
 * Tesla JSON API
 * API for controlling Tesla vehicles
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jonahwh.tesla_api_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.github.jonahwh.tesla_api_client.model.Vehicle;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * GetVehiclesResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-06T22:38:49.853-08:00[America/Los_Angeles]")
public class GetVehiclesResponse {
  @SerializedName("response")
  private List<Vehicle> response = new ArrayList<Vehicle>();

  @SerializedName("count")
  private Integer count = null;

  public GetVehiclesResponse response(List<Vehicle> response) {
    this.response = response;
    return this;
  }

  public GetVehiclesResponse addResponseItem(Vehicle responseItem) {
    this.response.add(responseItem);
    return this;
  }

   /**
   * Get response
   * @return response
  **/
  @Schema(required = true, description = "")
  public List<Vehicle> getResponse() {
    return response;
  }

  public void setResponse(List<Vehicle> response) {
    this.response = response;
  }

  public GetVehiclesResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @Schema(example = "1", required = true, description = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetVehiclesResponse getVehiclesResponse = (GetVehiclesResponse) o;
    return Objects.equals(this.response, getVehiclesResponse.response) &&
        Objects.equals(this.count, getVehiclesResponse.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(response, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetVehiclesResponse {\n");
    
    sb.append("    response: ").append(toIndentedString(response)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
