/*
 * Tesla JSON API
 * API for controlling Tesla vehicles
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jonahwh.tesla_api_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RemoteAutoSeatClimateRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-12-06T22:38:49.853-08:00[America/Los_Angeles]")
public class RemoteAutoSeatClimateRequest {
  /**
   * The desired seat to toggle auto mode for.  SeatHeaterFrontLeft: 0, SeatHeaterFrontRight: 1, SeatHeaterRearLeft: 2, SeatHeaterRearLeftBack: 3, SeatHeaterRearCenter: 4, SeatHeaterRearRight: 5, SeatHeaterRearRightBack: 6, SeatHeater3rdRowLeft: 7, SeatHeater3rdRowRight: 8
   */
  @JsonAdapter(AutoSeatPositionEnum.Adapter.class)
  public enum AutoSeatPositionEnum {
    NUMBER_0(0),
    NUMBER_1(1),
    NUMBER_2(2),
    NUMBER_3(3),
    NUMBER_4(4),
    NUMBER_5(5),
    NUMBER_6(6),
    NUMBER_7(7),
    NUMBER_8(8);

    private Integer value;

    AutoSeatPositionEnum(Integer value) {
      this.value = value;
    }
    public Integer getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AutoSeatPositionEnum fromValue(Integer input) {
      for (AutoSeatPositionEnum b : AutoSeatPositionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AutoSeatPositionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AutoSeatPositionEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AutoSeatPositionEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextInt();
        return AutoSeatPositionEnum.fromValue((Integer)(value));
      }
    }
  }  @SerializedName("auto_seat_position")
  private AutoSeatPositionEnum autoSeatPosition = null;

  @SerializedName("auto_climate_on")
  private Boolean autoClimateOn = null;

  public RemoteAutoSeatClimateRequest autoSeatPosition(AutoSeatPositionEnum autoSeatPosition) {
    this.autoSeatPosition = autoSeatPosition;
    return this;
  }

   /**
   * The desired seat to toggle auto mode for.  SeatHeaterFrontLeft: 0, SeatHeaterFrontRight: 1, SeatHeaterRearLeft: 2, SeatHeaterRearLeftBack: 3, SeatHeaterRearCenter: 4, SeatHeaterRearRight: 5, SeatHeaterRearRightBack: 6, SeatHeater3rdRowLeft: 7, SeatHeater3rdRowRight: 8
   * @return autoSeatPosition
  **/
  @Schema(description = "The desired seat to toggle auto mode for.  SeatHeaterFrontLeft: 0, SeatHeaterFrontRight: 1, SeatHeaterRearLeft: 2, SeatHeaterRearLeftBack: 3, SeatHeaterRearCenter: 4, SeatHeaterRearRight: 5, SeatHeaterRearRightBack: 6, SeatHeater3rdRowLeft: 7, SeatHeater3rdRowRight: 8")
  public AutoSeatPositionEnum getAutoSeatPosition() {
    return autoSeatPosition;
  }

  public void setAutoSeatPosition(AutoSeatPositionEnum autoSeatPosition) {
    this.autoSeatPosition = autoSeatPosition;
  }

  public RemoteAutoSeatClimateRequest autoClimateOn(Boolean autoClimateOn) {
    this.autoClimateOn = autoClimateOn;
    return this;
  }

   /**
   * Whether to enable or disable auto climate mode
   * @return autoClimateOn
  **/
  @Schema(description = "Whether to enable or disable auto climate mode")
  public Boolean isAutoClimateOn() {
    return autoClimateOn;
  }

  public void setAutoClimateOn(Boolean autoClimateOn) {
    this.autoClimateOn = autoClimateOn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteAutoSeatClimateRequest remoteAutoSeatClimateRequest = (RemoteAutoSeatClimateRequest) o;
    return Objects.equals(this.autoSeatPosition, remoteAutoSeatClimateRequest.autoSeatPosition) &&
        Objects.equals(this.autoClimateOn, remoteAutoSeatClimateRequest.autoClimateOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoSeatPosition, autoClimateOn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteAutoSeatClimateRequest {\n");
    
    sb.append("    autoSeatPosition: ").append(toIndentedString(autoSeatPosition)).append("\n");
    sb.append("    autoClimateOn: ").append(toIndentedString(autoClimateOn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
